In [ ]:

# Create a dictionary and apply the following Methods: 1) Print the dictionary items 2) access items 3) use get() 4)change values 5) use len()
thisdict = {
  'brand': 'Ford',
  'model': 'Mustang',
  'year': 1964
}
# to print a dict
print(thisdict)
#To access the elements
print(thisdict["brand"])
#accessing the elements by using get()
print(thisdict.get("model"))
#update the data
thisdict["year"]="1974"
print(thisdict)
#using len() to find the no of data stored in dict
print(len(thisdict))

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Ford
Mustang
{'brand': 'Ford', 'model': 'Mustang', 'year': '1974'}
3

In [ ]:
#Write a program to check whether an entered character (alphabet) is an uppercase alphabet, lowercase alphabet or a special character.
char=input('Enter a letter')
if char>='A' and char<='Z':
  print('The char is in upper case')
elif char<='a' and char>='z':
  print('The char is in lower case')
else :
  print('The char is special char')

Enter a letterA
The char is in upper case

In [4]:

#Write a program to implement simple calculator
num1=float(input("Enter the first no :"))
operator=input("+,-,*,/,**,%")
num2=float(input("Enter the second no :"))
operator=input("+,-,*,/,**,%")
num3=float(input("Enter the third no :"))
if operator=='+':
  print(num1+num2+num3)
elif operator=='-':
  print(num1-num2-num3)
elif operator=='*':
  print(num1*num2*num3)
elif operator=='**':
  print(num1**num2**num3)
elif operator=='/':
  print(num1/num2/num3)
elif operator=='%':
  print(num1%num2%num3)
else :
  print("Invalid char Enter")

Enter the first no :20
+,-,*,/,**,%+
Enter the second no :30
+,-,*,/,**,%-
Enter the third no :20
-30.0

In [ ]:
#Write a program to check whether the entered no is even or odd.
num=float(input("Enter No :"))
if num%2==0:
  print("The no is even")
else :
  print("The no is odd")

Enter No :2
The no is even

In [ ]:
#Write a program that checks if a given year is a leap year. A leap year is divisible by 4, but not by 100, unless it is also divisible by 400.
year=int(input("enter year"))
if year%4==0 and year/100!=0 or year%400==0:
  (print("The year is leap year"))
else :
  print("The year is not leap year")

enter year2016
The year is leap year

In [ ]:
#Write a program that takes a person's age as input and classifies them into one of the following groups:

#0-12: Child

#13-19: Teenager

#20-59: Adult
age=int(input("Enter age"))
if age>=0 and age<=12:
  print("Child")
elif age>=13 and age<=19:
  print("Teenager")
elif age>=20 and age<=59:
  print("Adult")

Enter age12
Child

In [1]:
#Write a program to find the largest number in a list using user defined function.

def find_largest(numbers):

    largest = numbers[0]
    for num in numbers:
        if num > largest:
            largest = num

    return largest
a=int(input("Enter number seperated by space :"))
for x in a :
largest_number = find_largest(numbers)
print("The largest number is:", largest_number)

ValueError: invalid literal for int() with base 10: '10 20 30 40 '

In [ ]:
#Write a lambda function to check if a no is even or odd
check_even_odd = lambda x: "Even" if x % 2 == 0 else "Odd"
number = int(input("Enter a number: "))
result = check_even_odd(number)
print(result)

Enter a number: 15
Odd

In [ ]:
#Write a program illustrating the concept of break.

for i in range(1, 11):
    if i == 7:
        print("Breaking the loop because i is 7")
        break


    print(f"{i}")

1
2
3
4
5
6
Breaking the loop because i is 7

In [ ]:
#Write a program illustrating the concept of continue.
for i in range(1,11):
  if i==2:
    print("continue")
    continue
  print(i)

1
continue
3
4
5
6
7
8
9
10

In [ ]:
#write a program for a list to break at a point
list=[12,15,'a','b','c']
for i in list:
  print(i)
  if i=='b':
    break

12
15
a
b

In [ ]:
#write a program for a list to skip and continue
list=[12,15,'a','b','c']
for i in list:
  print(i)
  if i == 12:
    print("skip the elements")
    continue
    print(i)

12
skip the elements
15
a
b
c

In [ ]:
#write a program for a tuple to break
my_tuple = (10, 20, 30, 40, 50)
for i in my_tuple:
    if i == 30:
        print("breaking the loop.")
        break
    print(i)

10
20
breaking the loop.

In [ ]:
#write a program for a tuple to continue
my_tuple = (10, 20, 30, 40, 50)
for i in my_tuple:
    if i == 30:
        print("skipping the loop.")
        continue
    print(i)

10
20
skipping the loop.
40
50

In [2]:
#Write a program to find the factorial of a number using functions.

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result


num = int(input("Enter a number to find its factorial: "))


print("The factorial of ", num , "is", factorial(num))

Enter a number to find its factorial: 7
The factorial of  7 is 5040

In [ ]:
#Write a program to add two numbers using functions.(Function should return the sum to calling function)
def sum(a,b):
  return a+b
a=int(input("Enter the first no :"))
b=int(input("Enter the second no :"))
print(sum(a,b))

Enter the first no :1
Enter the second no :3
4

In [ ]:
#Write a program illustratating the use of default arguments and keyword arguments in function.
def student(firstname, lastname ='kumar', standard ='Fifth'):
     print(firstname, lastname, 'studies in', standard, 'Standard')


student('Rahul')
student('Virat', 'Kohli', 'Seventh')
student('Rohit', 'sharma')

Rahul kumar studies in Fifth Standard
Virat Kohli studies in Seventh Standard
Rohit sharma studies in Fifth Standard

In [ ]:
#Write a program to print the following pattern
#1
#1 1
#1 1 1
#1 1  1 1
#1  1  1 1 1
rows = 5

for i in range(1, rows + 1):
    # Print '1' i times in each row
    print("1 " * i)

1
1 1
1 1 1
1 1 1 1
1 1 1 1 1

In [ ]:
#Write a program to print the following pattern
#1
#1 2
#1 2 3
#1 2 3 4
#1  2  3 4 5
rows = 5
for i in range(1, rows + 1):

    for j in range(1, i + 1):
        print(j, end=" ")
    print()

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5